version: '3.8'

services:
  # localstack:
  #   container_name: localstack
  #   image: localstack/localstack:latest
  #   ports:
  #     - "127.0.0.1:4566:4566"            # LocalStack Gateway
  #     - "127.0.0.1:4510-4559:4510-4559"  # external services port range
  #   environment:
  #     - SERVICES=s3,sqs,lambda,apigateway,dynamodb,cloudformation,logs,iam
  #     - DEBUG=1
  #     - ENFORCE_IAM=1
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #   volumes:
  #     - localstack:/var/lib/localstack
  #     - "/var/run/docker.sock:/var/run/docker.sock"

  mongo:
    image: mongo:latest
    container_name: 'mongodb'
    volumes:
      - mongodb:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      - MONGO_INITDB_DATABASE=tasks
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
    networks:
      - tasks-network

  sqs:
    image: softwaremill/elasticmq-native
    container_name: 'sqs'
    ports:
        - 9324:9324
        - 9325:9325
    volumes:
        - ./sqs-offline.conf:/opt/elasticmq.conf
    networks:
        - tasks-network
      
volumes:
  localstack:
  mongodb:

networks:
  tasks-network:
    driver: bridge